### PR TITLE
updating duo_web.php after format injection fix

### PR DESCRIPTION
**Pull request by erikbarbara**
Updating duo_web.php with the most recent version at https://github.com/duosecurity/duo_php. There was a format injection vulnerability patched a month ago.

### CODE REVIEW

**Comment by knastase** [comment]
Thanks Erik!

**Comment by erikbarbara** [comment]
Hi Kevin,

I noticed that there's no license on this repo. Would you consider adding
one so it's clearer how end-users can use it? Maybe an MIT license?

Thanks!

Erik

**Comment by knastase** [comment]
Sure thing! MIT license added.

**Comment by erikbarbara** [comment]
Great. I folded your license in to my fork. :)

**Pull request merged**
